In [ ]:
import pandas as pd
from cyvcf2 import VCF

In [ ]:
vcf = list(VCF('/Users/quinlan/Documents/Git/SEMIColon/data/test_donor091_snp_chunk_chr21.vcf'))


In [11]:
    # gt_types is array of 0,1,2,3==HOM_REF, HET, UNKNOWN, HOM_ALT
HOM_REF=0
HET=1
UNKNOWN=2
HOM_ALT=3


In [ ]:
# for v in vcf:
#     #SNVs = [v for v in vcf if v.INFO.get('TYPE') == 'snp']
#     print(v.genotype)
#     print(v.QUAL)
#     print(v.gt_depths)


In [15]:
# for v in vcf:
#     if v.QUAL>20:
#         print(v.gt_types, v.gt_ref_depths, v.gt_alt_depths)

[3 2 2] [ 0 -1 -1] [ 2 -1 -1]
[3 3 2] [ 0  0 -1] [ 2  1 -1]
[1 1 0] [4 1 3] [3 3 0]
[3 3 2] [ 0  0 -1] [ 7  3 -1]
[1 3 0] [4 0 1] [2 2 0]
[1 1 3] [3 2 0] [4 1 2]
[1 1 3] [4 2 0] [4 1 2]
[3 3 3] [0 0 0] [9 3 1]
[1 1 0] [5 2 1] [4 2 0]
[1 1 2] [ 3  2 -1] [ 3  3 -1]
[1 1 2] [ 2  2 -1] [ 5  2 -1]
[1 1 2] [ 0  0 -1] [7 6 2]
[1 1 0] [4 5 1] [5 4 0]
[1 1 3] [5 4 0] [4 3 2]
[3 3 3] [0 0 0] [6 6 2]
[1 1 2] [ 6  4 -1] [ 4  2 -1]
[3 3 3] [0 0 0] [13  5  2]
[1 0 0] [3 2 2] [6 1 0]
[1 0 3] [3 2 0] [6 1 1]
[1 0 0] [5 1 1] [4 1 0]
[1 0 2] [ 7  3 -1] [ 6  1 -1]
[1 0 0] [6 4 1] [4 0 0]
[1 1 0] [6 4 1] [5 1 0]
[1 1 3] [5 1 0] [5 4 2]
[1 1 0] [3 5 3] [5 3 0]
[1 1 0] [2 5 3] [5 2 0]
[1 1 2] [ 7  5 -1] [ 4  2 -1]
[3 3 3] [0 0 0] [8 2 2]
[3 3 3] [0 0 0] [5 2 3]
[1 2 3] [ 2 -1  1] [ 2 -1  3]
[1 3 1] [5 0 1] [2 1 1]
[1 1 0] [3 3 1] [2 3 0]
[3 3 2] [ 0  0 -1] [ 4  6 -1]
[3 2 1] [ 0 -1  1] [ 3 -1  2]
[3 0 2] [ 1  2 -1] [ 5  0 -1]
[3 3 3] [0 0 0] [7 3 1]
[1 1 1] [5 1 1] [4 1 1]
[1 1 1] [5 1 1] [4 1 1]
[1 3 0] [3

In [ ]:
# for variant in vcf:
#     if variant.QUAL>20:
#         print(variant.genotype, variant.gt_ref_depths, variant.gt_alt_depths) # numpy arrays
#         print(variant.format("DP"))


In [20]:
# gt_types is array of 0,1,2,3==HOM_REF, HET, UNKNOWN, HOM_ALT
for v in vcf:
    if v.QUAL>20:
        genotypes = v.gt_types
        if genotypes[0] == HET & genotypes[1] == HET & genotypes[2] == HET:
            continue
        elif genotypes[0] == HOM_REF & genotypes[1] == HOM_REF & genotypes[2] == HOM_REF:
            continue
        elif genotypes[0] == HOM_ALT & genotypes[1] == HOM_ALT & genotypes[2] == HOM_ALT:
            continue
        elif genotypes[1] == UNKNOWN:
            continue
        elif genotypes[0] == UNKNOWN & genotypes[2] == UNKNOWN:
            continue
        else:
            print(v.gt_types)

[3 3 2]
[1 1 0]
[3 3 2]
[1 3 0]
[1 1 0]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 0]
[1 1 2]
[1 0 0]
[1 0 3]
[1 0 0]
[1 0 2]
[1 0 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 2]
[1 1 0]
[3 3 2]
[3 0 2]
[1 3 0]
[1 1 0]
[1 0 2]
[1 0 2]
[1 3 2]
[3 3 2]
[1 1 2]
[1 1 2]
[1 0 2]
[3 3 2]
[3 3 0]
[3 3 2]
[3 3 2]
[1 0 2]
[1 0 2]
[1 1 2]
[1 1 2]
[1 1 0]
[1 0 2]
[1 0 2]
[1 1 0]
[1 3 0]
[3 3 0]
[1 3 0]
[1 3 2]
[1 3 0]
[1 1 0]
[1 1 0]
[1 1 0]
[1 3 2]
[1 3 2]
[1 1 0]
[1 1 0]
[3 1 2]
[3 3 2]
[3 3 2]
[3 3 2]
[1 3 2]
[1 3 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 0]
[1 1 0]
[1 1 2]
[1 1 2]
[1 1 0]
[1 1 0]
[1 1 0]
[1 1 2]
[3 3 2]
[1 3 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 2]
[3 3 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 0 0]
[1 1 2]
[1 0 0]
[1 0 0]
[3 3 2]
[3 3 2]
[3 3 1]
[3 3 0]
[1 1 2]
[1 1 2]
[1 0 1]
[1 1 0]
[3 0 3]
[3 3 2]
[1 0 3]
[1 1 2]
[1 1 0]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 2]
[1 0 0]
[3 3 2]
[1 1 0]
[1 1 2]
[1 1 2]
[1 1 2]
[1 1 0]
[1 1 2]
[1 0 0]
[1 0 0]
[1 1 2]
[3 1 2]
[1 1 2]
